#!/bin/bash

gcd () { 
if [ $1 -eq 0 ]
then 
	return $2
fi 
gcd `expr $2 % $1` $1
next=$?
return $next
}
IFS=','
val=($@)

if [ ${#val[@]} -eq 1 ]
then
	echo "$1"
	exit 0
elif [ ${#val[@]} -eq 0 ]
then
	exit 0
fi

if [ ${#val[@]} -lt 10 ]
then
	res=${val[0]}
	i=1
	while [ $i -lt ${#val[@]} ]
	do
		gcd $res ${val[$i]}
		res=$?
		i=`expr $i + 1`
	done
fi
echo "$res"
